server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # Route requests for /auth/** to the http://auth-service:4005/login
        ## REST CLIENT to api gateway-> http://localhost:4004/auth/login
        ## API GATEWAY will apply the filter and forward the request to -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route requests for /api/patients/** to the patient-service
        ## REST CLIENT -> http://localhost:4004/api/patients
        ## API GATEWAY -> http://patient-service:4000/patients
        ## PATIENT SERVICE ( Spring boot app ) -> patients -> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ## REST-CLIENT -> http://localhost:4004/api-docs/patients
        ## API-GATEWAY -> http://patients-service:4000/v3/api-docs
        # Route for /api/docs/patients to patients-service/v3/api-docs
        - id: api-docs-patient-rout
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

