### Updates an existing new patinet
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name":"john doe UPDATED 2 ",
  "email": "john.doe@example.com",
  "address": "235 Giza Egypt",
  "dateOfBirth": "1992-08-15"
}


###